spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.198:3306/shark_user?characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name: service-hystrix-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9200
ribbon:
  connectTimeout: 4000